spring:
  application:
    name: EurekaServer
  #main:
   # allow-bean-definition-overriding: true

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/